# Generated by Django 5.1.2 on 2024-10-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'رویداد', 'verbose_name_plural': 'رویدادها'},
        ),
        migrations.AlterModelOptions(
            name='eventfeature',
            options={'verbose_name': 'ویژگی رویداد', 'verbose_name_plural': 'ویژگی های رویداد'},
        ),
        migrations.AlterModelOptions(
            name='usereventrole',
            options={'verbose_name': 'نقش کاربر در رویداد', 'verbose_name_plural': 'نقش کاربرها در رویداد'},
        ),
        migrations.AlterUniqueTogether(
            name='usereventrole',
            unique_together=set(),
        ),
    ]
