# Generated by Django 5.1.2 on 2024-11-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0002_alter_event_options_alter_eventfeature_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='event',
            name='province',
        ),
        migrations.AddField(
            model_name='event',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
