# Generated by Django 5.1.2 on 2024-11-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0003_remove_event_city_remove_event_neighborhood_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_by',
            new_name='event_owner',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='تهران', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='province',
            field=models.CharField(default='تهران', max_length=100),
        ),
    ]
