# Generated by Django 5.1.2 on 2024-12-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
