# Generated by Django 5.1.2 on 2025-01-23 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0008_notificationstatus'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usereventrole',
            unique_together={('user', 'event')},
        ),
    ]
