version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=False
      - DB_NAME=Yekikame
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app
      - static_volume:/app/static_media  # Share static files with Nginx
    command: >
      sh -c "./wait-for-it.sh db:5432 -- 
             python manage.py migrate &&
             python manage.py test &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: Yekikame
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Link Nginx config
      - static_volume:/app/static_media              # Serve static files from volume
    restart: always

volumes:
  postgres_data:
  static_volume:
