# Generated by Django 5.1.2 on 2024-12-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='No Name', max_length=250, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=255, verbose_name='عنوان سوال')),
                ('question_answer', models.TextField(verbose_name='جواب سوال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user', verbose_name='کاربر ایجاد کننده')),
            ],
            options={
                'verbose_name': 'پرسش متداول',
                'verbose_name_plural': 'پرسش\u200cهای متداول',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تیکت')),
                ('content', models.TextField(verbose_name='متن تیکت')),
                ('department', models.CharField(choices=[('technical', 'دپارتمان فنی'), ('financial', 'دپارتمان مالی')], max_length=20, verbose_name='دپارتمان تیکت')),
                ('priority', models.CharField(choices=[('high', 'زیاد'), ('medium', 'متوسط'), ('low', 'کم')], default='medium', max_length=10, verbose_name='اهمیت تیکت')),
                ('status', models.CharField(choices=[('waiting', 'منتظر پاسخ'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='waiting', max_length=10, verbose_name='وضعیت تیکت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user', verbose_name='کاربر ایجاد کننده')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Support.ticket', verbose_name='تیکت مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200cهای تیکت',
            },
        ),
    ]
