# Generated by Django 5.1.2 on 2024-12-22 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان اطلاعیه')),
                ('content', models.TextField(verbose_name='متن اطلاعیه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد اطلاعیه')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت اطلاعیه')),
                ('expiration_date', models.DateTimeField(verbose_name='تاریخ انقضای اطلاعیه')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='userapp.user', verbose_name='کاربر سازنده اطلاعیه')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
            },
        ),
    ]
