# Generated by Django 5.1.2 on 2024-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(default='No Name', max_length=250, verbose_name='نام و نام خانوادگی'),
        ),
    ]
