# Generated by Django 5.1.2 on 2024-11-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_otp_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
