name: Docker CI/CD

on:
  push:
    branches:
      - Main        # Trigger the workflow on push to the 'Main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t fivegunners/yekikame:latest .
        docker push fivegunners/yekikame:latest

    # Step 5: Deploy to VPS
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/YekiKameDjango_Org
            if [ -d "YekiKameDjango_Org" ]; then
            echo "Project exists. Pulling latest changes..."
            cd YekiKameDjango_Org
            git reset --hard  # Reset any local changes
            git pull origin Main  # Pull the latest code
          else
            echo "Project does not exist. Cloning repository..."
            git clone https://github.com/YekiKame/YekiKameDjango_Org.git YekiKameDjango_Org
            cd YekiKameDjango_Org
          fi
      
            # Deploy with Docker Compose
            docker-compose down
            docker-compose pull
            docker-compose up -d --force-recreate
